//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMConfig_tb
    {
        public int idCOM { get; set; }
        public string COMConfig { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
    }
}
