//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condicao_tb
    {
        public int idCondicao { get; set; }
        public Nullable<int> idFuncao { get; set; }
        public string Estado { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Funcoes_tb Funcoes_tb { get; set; }
        public virtual user user { get; set; }
    }
}
