//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departamento
    {
        public departamento()
        {
            this.PermissaoDeparramento_tb = new HashSet<PermissaoDeparramento_tb>();
            this.pastadepartamento = new HashSet<pastadepartamento>();
        }
    
        public int iddepartamento { get; set; }
        public string NomeDepartamento { get; set; }
        public string DescricaoDepartamanto { get; set; }
        public string GuidMap { get; set; }
    
        public virtual ICollection<PermissaoDeparramento_tb> PermissaoDeparramento_tb { get; set; }
        public virtual ICollection<pastadepartamento> pastadepartamento { get; set; }
    }
}
