//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documentosenviados
    {
        public int idDocumentosEnviados { get; set; }
        public string NomeDocumento { get; set; }
        public byte[] Ficheiro { get; set; }
        public string Extensao { get; set; }
        public Nullable<int> idEnvio { get; set; }
        public string Contentype { get; set; }
        public string GuidMap { get; set; }
    
        public virtual EnviarDocumentos EnviarDocumentos { get; set; }
    }
}
