//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class documento
    {
        public int iddocumento { get; set; }
        public string NomeDocumento { get; set; }
        public string Descricao { get; set; }
        public string Destaque { get; set; }
        public Nullable<int> idPastaDocumento { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public Nullable<System.DateTime> DateUpload { get; set; }
        public string GuidMap { get; set; }
    }
}
