//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instituicao_tb
    {
        public int idinstituicao { get; set; }
        public string Nome { get; set; }
        public string Extensao { get; set; }
        public string Localizacao { get; set; }
        public string Telefone { get; set; }
        public string Email { get; set; }
        public string NUIT { get; set; }
        public string Slogan { get; set; }
        public byte[] Logo { get; set; }
    }
}
