//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimentacao_Documentos_tb
    {
        public int idMovimentacao { get; set; }
        public Nullable<int> idusuario { get; set; }
        public Nullable<int> idOrigem { get; set; }
        public Nullable<int> idDestino { get; set; }
        public Nullable<System.DateTime> DataMovimentacao { get; set; }
        public string DescricaoMovimentacao { get; set; }
    }
}
