//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class pastadepartamento
    {
        public pastadepartamento()
        {
            this.RecebimentoDocumentos = new HashSet<RecebimentoDocumentos>();
            this.Cartas_tb = new HashSet<Cartas_tb>();
        }
    
        public int idpastadepartamento { get; set; }
        public string NomePasta { get; set; }
        public int idDepartamento { get; set; }
        public string GuidMap { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual ICollection<RecebimentoDocumentos> RecebimentoDocumentos { get; set; }
        public virtual ICollection<Cartas_tb> Cartas_tb { get; set; }
    }
}
