//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedidos_tb
    {
        public Pedidos_tb()
        {
            this.Cartas_tb = new HashSet<Cartas_tb>();
        }
    
        public int idPedidos { get; set; }
        public string Pedido { get; set; }
        public string DescricaoPedido { get; set; }
    
        public virtual ICollection<Cartas_tb> Cartas_tb { get; set; }
    }
}
