//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissaoDeparramento_tb
    {
        public int idPermissao { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idDepartamento { get; set; }
        public Nullable<System.DateTime> DataRegisto { get; set; }
        public string Estado { get; set; }
        public string GuidMap { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual user user { get; set; }
    }
}
