//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecebimentoDocumentos
    {
        public int idRecebimento { get; set; }
        public Nullable<System.DateTime> DataRecebimento { get; set; }
        public Nullable<int> idEnvio { get; set; }
        public Nullable<int> idPastaDepartamento { get; set; }
        public string Informacao { get; set; }
        public string GuidMap { get; set; }
    
        public virtual EnviarDocumentos EnviarDocumentos { get; set; }
        public virtual pastadepartamento pastadepartamento { get; set; }
    }
}
