//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespostaCartas_tb
    {
        public int idResposta { get; set; }
        public Nullable<int> idCarta { get; set; }
        public Nullable<System.DateTime> DataResposta { get; set; }
        public string Resposta { get; set; }
        public string Nota { get; set; }
    
        public virtual Cartas_tb Cartas_tb { get; set; }
    }
}
