//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespostaDocumentoUsuario_tb
    {
        public int idRespostaDocumentoUsuario { get; set; }
        public Nullable<int> idDocumentoUser { get; set; }
        public string Resposta { get; set; }
        public Nullable<System.DateTime> DataResposta { get; set; }
        public Nullable<System.TimeSpan> HoraResposta { get; set; }
        public Nullable<int> idUserResposta { get; set; }
        public string Estado { get; set; }
    
        public virtual DocumentoUsuario_tb DocumentoUsuario_tb { get; set; }
    }
}
