//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RespostaDocumento
    {
        public int idResposta { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<int> idEnvio { get; set; }
        public Nullable<System.DateTime> DatResposta { get; set; }
        public string Resposta { get; set; }
        public string Comentario { get; set; }
        public string GuidMap { get; set; }
    
        public virtual EnviarDocumentos EnviarDocumentos { get; set; }
        public virtual user user { get; set; }
    }
}
