//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sms_tb
    {
        public int idSms { get; set; }
        public string NumeroTelefone { get; set; }
        public string Mensagem { get; set; }
        public Nullable<System.DateTime> DataEnvio { get; set; }
        public string Estado { get; set; }
        public string GuidMap { get; set; }
    }
}
