//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submissao_tb
    {
        public int idSubmissao { get; set; }
        public string Nome_completo { get; set; }
        public Nullable<int> idCurso { get; set; }
        public string Tema { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> id_Supervisor { get; set; }
        public Nullable<System.DateTime> Data_Submissao { get; set; }
        public Nullable<System.DateTime> Data_Registo { get; set; }
        public string Estado { get; set; }
        public string Contacto_Estudante { get; set; }
        public string Codigo_Projecto { get; set; }
        public Nullable<int> id_Secretaria_Confirmacao { get; set; }
        public string Guidmap { get; set; }
        public Nullable<int> id_vaga_submissao { get; set; }
    
        public virtual Curso_tb Curso_tb { get; set; }
        public virtual Supervisor_mono_tb Supervisor_mono_tb { get; set; }
        public virtual Vagas_Submissao_tb Vagas_Submissao_tb { get; set; }
    }
}
