//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Supervisor_mono_tb
    {
        public Supervisor_mono_tb()
        {
            this.Submissao_tb = new HashSet<Submissao_tb>();
        }
    
        public int idSupervisor { get; set; }
        public string Nome_completo { get; set; }
        public string Departamento { get; set; }
        public string Contacto { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<Submissao_tb> Submissao_tb { get; set; }
    }
}
