//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_usuario_tb
    {
        public Tipo_usuario_tb()
        {
            this.user = new HashSet<user>();
        }
    
        public int id_tipo_usuario { get; set; }
        public string Nome_tipo { get; set; }
        public string Descricao { get; set; }
    
        public virtual ICollection<user> user { get; set; }
    }
}
