//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoFuncao_tb
    {
        public TipoFuncao_tb()
        {
            this.Funcoes_tb = new HashSet<Funcoes_tb>();
        }
    
        public int idTipoFuncao { get; set; }
        public string NomeTipo { get; set; }
        public string Descricao { get; set; }
        public string GuidMap { get; set; }
    
        public virtual ICollection<Funcoes_tb> Funcoes_tb { get; set; }
    }
}
