//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public user()
        {
            this.Condicao_tb = new HashSet<Condicao_tb>();
            this.EnviarDocumentos = new HashSet<EnviarDocumentos>();
            this.PermissaoDeparramento_tb = new HashSet<PermissaoDeparramento_tb>();
            this.RespostaDocumento = new HashSet<RespostaDocumento>();
        }
    
        public int idUser { get; set; }
        public string NomeUsuario { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public string GuidMap { get; set; }
    
        public virtual ICollection<Condicao_tb> Condicao_tb { get; set; }
        public virtual ICollection<EnviarDocumentos> EnviarDocumentos { get; set; }
        public virtual ICollection<PermissaoDeparramento_tb> PermissaoDeparramento_tb { get; set; }
        public virtual ICollection<RespostaDocumento> RespostaDocumento { get; set; }
    }
}
