//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vagas_Submissao_tb
    {
        public Vagas_Submissao_tb()
        {
            this.Submissao_tb = new HashSet<Submissao_tb>();
        }
    
        public int id_vaga_submissao { get; set; }
        public string Titulo { get; set; }
        public Nullable<System.DateTime> Data_inicio { get; set; }
        public Nullable<System.DateTime> Data_fim { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> idOwner { get; set; }
        public string Estado { get; set; }
        public string Guidmap { get; set; }
        public Nullable<int> Ano { get; set; }
    
        public virtual ICollection<Submissao_tb> Submissao_tb { get; set; }
    }
}
