//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_PermissaoDepartamento
    {
        public int idUser { get; set; }
        public string NomeUsuario { get; set; }
        public string Email { get; set; }
        public int idPermissao { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public Nullable<System.DateTime> DataRegisto { get; set; }
        public string Estado { get; set; }
        public int iddepartamento { get; set; }
        public string NomeDepartamento { get; set; }
        public string GuidDepartamento { get; set; }
        public string GuidPermissaoDepartamento { get; set; }
        public string GuidUser { get; set; }
    }
}
