//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Expedientes
    {
        public int idEnvio { get; set; }
        public Nullable<System.DateTime> DataEnvio { get; set; }
        public string Estado { get; set; }
        public string Mensagem { get; set; }
        public string Titulo { get; set; }
        public string Contacto { get; set; }
        public string NivelUrgencia { get; set; }
        public string NomeCategoria { get; set; }
        public string NomeUsuario { get; set; }
        public string Email { get; set; }
        public string Senha { get; set; }
        public int idpastadepartamento { get; set; }
        public string NomePasta { get; set; }
        public int iddepartamento { get; set; }
        public string NomeDepartamento { get; set; }
        public int idUser { get; set; }
        public int idCategoria { get; set; }
        public string GuidDepartamento { get; set; }
        public string GuidPastaDepartamento { get; set; }
        public string GuidEnviarDocumento { get; set; }
        public string GuidCategoria { get; set; }
        public string GuidUser { get; set; }
    }
}
