//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Pastas
    {
        public int iddepartamento { get; set; }
        public string NomeDepartamento { get; set; }
        public int idpastadepartamento { get; set; }
        public string NomePasta { get; set; }
        public string GuidDepartamento { get; set; }
        public string GuidPastaDepartamento { get; set; }
    }
}
