//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Submissao
    {
        public int idSubmissao { get; set; }
        public string Nome_completo { get; set; }
        public string Tema { get; set; }
        public string Tipo { get; set; }
        public Nullable<System.DateTime> Data_Submissao { get; set; }
        public Nullable<System.DateTime> Data_Registo { get; set; }
        public string Estado { get; set; }
        public string Contacto_Estudante { get; set; }
        public string Codigo_Projecto { get; set; }
        public string Guidmap { get; set; }
        public byte[] Documento { get; set; }
        public int idCurso { get; set; }
        public string Curso { get; set; }
        public int idSupervisor { get; set; }
        public string Expr1 { get; set; }
        public string Departamento { get; set; }
        public string Contacto { get; set; }
        public int id_vaga_submissao { get; set; }
        public string Expr2 { get; set; }
    }
}
