//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_Recebimentos
    {
        public int idRecebimento { get; set; }
        public Nullable<System.DateTime> DataRecebimento { get; set; }
        public Nullable<int> idPastaDepartamento { get; set; }
        public string Informacao { get; set; }
        public int idEnvio { get; set; }
        public Nullable<System.DateTime> DataEnvio { get; set; }
        public Nullable<int> idUsuario { get; set; }
        public string Estado { get; set; }
        public string Titulo { get; set; }
        public string Contacto { get; set; }
        public string NivelUrgencia { get; set; }
        public string NomeCategoria { get; set; }
        public string DescricaoCategoria { get; set; }
        public int idCategoria { get; set; }
        public string Mensagem { get; set; }
        public string GuidRecebimentoDocumento { get; set; }
        public string GuidEnviarDocumentos { get; set; }
        public string GuidCategoria { get; set; }
        public string CodExpediente { get; set; }
    }
}
